[variables]
NODE_VERSION = "18.20.5"

[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "npm cache clean --force",
  "npm install --no-audit --progress=false --timeout=300000"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm run preview"

[staticAssets]
dir = "dist"