[variables]
NODE_VERSION = "18.20.5"

[phases.setup]
nixPkgs = ["nodejs_18", "yarn"]

[phases.install]
cmds = [
  "yarn cache clean",
  "yarn install --frozen-lockfile --network-timeout 300000"
]

[phases.build]
cmds = [
  "yarn build"
]

[start]
cmd = "yarn preview"

[staticAssets]
dir = "dist"